name: Build and Publish

on:
  release:
    types: [created]

strategy:
  matrix:
    targetplatform: [x86, x64]
    targetpath: ./bin/release

runs-on: windows-latest

jobs:
  deploy:
    steps:
    - uses: actions/checkout@master
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.200
    - name: Build release
      run: dotnet publish --configuration Release --output ${{ matrix.targetpath }} --framework win-${{ matrix.targetplatform }} -p:PublishReadyToRun=true -p:PublishSingleFile=true -p:PublishTrimmed=true --self-contained true
    - name: Upload release
      uses: actions/upload-release-asset@v1.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ${{ matrix.targetpath }}
        asset_name: mosey-${{ github.event.release.tag_name }}-${{ matrix.targetplatform }}.exe
        asset_content_type: binary/octet-stream